modLoader = "kotlinforforge"
loaderVersion = "[5.3,)"
issueTrackerURL = "https://github.com/ConcerroX/emi-plus-plus/issues"
license = "MIT Licensed"

[[mods]]
modId = "emixx"
version = "${version}"
displayName = "EMI++"
authors = "ConcerroX, evanbones"
description = '''
Adds many useful features to EMI!
'''
logoFile = "icon.png"

[[mixins]]
config = "emixx.mixins.json"

[[mixins]]
config = "emixx-common.mixins.json"

[[dependencies.emixx]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.emixx]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "CLIENT"
